// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateBackupParams creates a new CreateBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBackupParams() *CreateBackupParams {
	return &CreateBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBackupParamsWithTimeout creates a new CreateBackupParams object
// with the ability to set a timeout on a request.
func NewCreateBackupParamsWithTimeout(timeout time.Duration) *CreateBackupParams {
	return &CreateBackupParams{
		timeout: timeout,
	}
}

// NewCreateBackupParamsWithContext creates a new CreateBackupParams object
// with the ability to set a context for a request.
func NewCreateBackupParamsWithContext(ctx context.Context) *CreateBackupParams {
	return &CreateBackupParams{
		Context: ctx,
	}
}

// NewCreateBackupParamsWithHTTPClient creates a new CreateBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBackupParamsWithHTTPClient(client *http.Client) *CreateBackupParams {
	return &CreateBackupParams{
		HTTPClient: client,
	}
}

/*
CreateBackupParams contains all the parameters to send to the API endpoint

	for the create backup operation.

	Typically these are written to a http.Request.
*/
type CreateBackupParams struct {

	// Body.
	Body CreateBackupBody

	/* ClusterID.

	   The ID of your cluster that you want to take a manual backup. You can get the cluster ID from the response of [Get all clusters in a project](#tag/Cluster/operation/ListClustersOfProject).

	   Format: uint64
	*/
	ClusterID string

	/* ProjectID.

	   The ID of your project. You can get the project ID from the response of [List all accessible projects.](#tag/Project/operation/ListProjects).

	   Format: uint64
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBackupParams) WithDefaults() *CreateBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create backup params
func (o *CreateBackupParams) WithTimeout(timeout time.Duration) *CreateBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create backup params
func (o *CreateBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create backup params
func (o *CreateBackupParams) WithContext(ctx context.Context) *CreateBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create backup params
func (o *CreateBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create backup params
func (o *CreateBackupParams) WithHTTPClient(client *http.Client) *CreateBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create backup params
func (o *CreateBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create backup params
func (o *CreateBackupParams) WithBody(body CreateBackupBody) *CreateBackupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create backup params
func (o *CreateBackupParams) SetBody(body CreateBackupBody) {
	o.Body = body
}

// WithClusterID adds the clusterID to the create backup params
func (o *CreateBackupParams) WithClusterID(clusterID string) *CreateBackupParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the create backup params
func (o *CreateBackupParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the create backup params
func (o *CreateBackupParams) WithProjectID(projectID string) *CreateBackupParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create backup params
func (o *CreateBackupParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
