// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBackupParams creates a new DeleteBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBackupParams() *DeleteBackupParams {
	return &DeleteBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBackupParamsWithTimeout creates a new DeleteBackupParams object
// with the ability to set a timeout on a request.
func NewDeleteBackupParamsWithTimeout(timeout time.Duration) *DeleteBackupParams {
	return &DeleteBackupParams{
		timeout: timeout,
	}
}

// NewDeleteBackupParamsWithContext creates a new DeleteBackupParams object
// with the ability to set a context for a request.
func NewDeleteBackupParamsWithContext(ctx context.Context) *DeleteBackupParams {
	return &DeleteBackupParams{
		Context: ctx,
	}
}

// NewDeleteBackupParamsWithHTTPClient creates a new DeleteBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBackupParamsWithHTTPClient(client *http.Client) *DeleteBackupParams {
	return &DeleteBackupParams{
		HTTPClient: client,
	}
}

/*
DeleteBackupParams contains all the parameters to send to the API endpoint

	for the delete backup operation.

	Typically these are written to a http.Request.
*/
type DeleteBackupParams struct {

	/* BackupID.

	   The ID of the backup. You can get the backup ID from the response of [List all backups for a cluster](#tag/Project/operation/ListBackUpOfCluster).

	   Format: uint64
	*/
	BackupID string

	/* ClusterID.

	   The ID of your cluster. You can get the cluster ID from the response of [Get all clusters in a project](#tag/Cluster/operation/ListClustersOfProject).

	   Format: uint64
	*/
	ClusterID string

	/* ProjectID.

	   The ID of your project. You can get the project ID from the response of [List all accessible projects.](#tag/Project/operation/ListProjects).

	   Format: uint64
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBackupParams) WithDefaults() *DeleteBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete backup params
func (o *DeleteBackupParams) WithTimeout(timeout time.Duration) *DeleteBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete backup params
func (o *DeleteBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete backup params
func (o *DeleteBackupParams) WithContext(ctx context.Context) *DeleteBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete backup params
func (o *DeleteBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete backup params
func (o *DeleteBackupParams) WithHTTPClient(client *http.Client) *DeleteBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete backup params
func (o *DeleteBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupID adds the backupID to the delete backup params
func (o *DeleteBackupParams) WithBackupID(backupID string) *DeleteBackupParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the delete backup params
func (o *DeleteBackupParams) SetBackupID(backupID string) {
	o.BackupID = backupID
}

// WithClusterID adds the clusterID to the delete backup params
func (o *DeleteBackupParams) WithClusterID(clusterID string) *DeleteBackupParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the delete backup params
func (o *DeleteBackupParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the delete backup params
func (o *DeleteBackupParams) WithProjectID(projectID string) *DeleteBackupParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete backup params
func (o *DeleteBackupParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param backup_id
	if err := r.SetPathParam("backup_id", o.BackupID); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
