// Code generated by go-swagger; DO NOT EDIT.

package import_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetImportTaskRoleInfoParams creates a new GetImportTaskRoleInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetImportTaskRoleInfoParams() *GetImportTaskRoleInfoParams {
	return &GetImportTaskRoleInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetImportTaskRoleInfoParamsWithTimeout creates a new GetImportTaskRoleInfoParams object
// with the ability to set a timeout on a request.
func NewGetImportTaskRoleInfoParamsWithTimeout(timeout time.Duration) *GetImportTaskRoleInfoParams {
	return &GetImportTaskRoleInfoParams{
		timeout: timeout,
	}
}

// NewGetImportTaskRoleInfoParamsWithContext creates a new GetImportTaskRoleInfoParams object
// with the ability to set a context for a request.
func NewGetImportTaskRoleInfoParamsWithContext(ctx context.Context) *GetImportTaskRoleInfoParams {
	return &GetImportTaskRoleInfoParams{
		Context: ctx,
	}
}

// NewGetImportTaskRoleInfoParamsWithHTTPClient creates a new GetImportTaskRoleInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetImportTaskRoleInfoParamsWithHTTPClient(client *http.Client) *GetImportTaskRoleInfoParams {
	return &GetImportTaskRoleInfoParams{
		HTTPClient: client,
	}
}

/*
GetImportTaskRoleInfoParams contains all the parameters to send to the API endpoint

	for the get import task role info operation.

	Typically these are written to a http.Request.
*/
type GetImportTaskRoleInfoParams struct {

	/* ClusterID.

	   The ID of your cluster. You can get the cluster ID from the response of [List all clusters in a project](#tag/Cluster/operation/ListClustersOfProject).

	   Format: uint64
	*/
	ClusterID string

	/* ProjectID.

	   The ID of your project. You can get the project ID from the response of [List all accessible projects](#tag/Project/operation/ListProjects).

	   Format: uint64
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get import task role info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImportTaskRoleInfoParams) WithDefaults() *GetImportTaskRoleInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get import task role info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetImportTaskRoleInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get import task role info params
func (o *GetImportTaskRoleInfoParams) WithTimeout(timeout time.Duration) *GetImportTaskRoleInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get import task role info params
func (o *GetImportTaskRoleInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get import task role info params
func (o *GetImportTaskRoleInfoParams) WithContext(ctx context.Context) *GetImportTaskRoleInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get import task role info params
func (o *GetImportTaskRoleInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get import task role info params
func (o *GetImportTaskRoleInfoParams) WithHTTPClient(client *http.Client) *GetImportTaskRoleInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get import task role info params
func (o *GetImportTaskRoleInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get import task role info params
func (o *GetImportTaskRoleInfoParams) WithClusterID(clusterID string) *GetImportTaskRoleInfoParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get import task role info params
func (o *GetImportTaskRoleInfoParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the get import task role info params
func (o *GetImportTaskRoleInfoParams) WithProjectID(projectID string) *GetImportTaskRoleInfoParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get import task role info params
func (o *GetImportTaskRoleInfoParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetImportTaskRoleInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
