// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateAccesspointParams creates a new CreateAccesspointParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAccesspointParams() *CreateAccesspointParams {
	return &CreateAccesspointParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAccesspointParamsWithTimeout creates a new CreateAccesspointParams object
// with the ability to set a timeout on a request.
func NewCreateAccesspointParamsWithTimeout(timeout time.Duration) *CreateAccesspointParams {
	return &CreateAccesspointParams{
		timeout: timeout,
	}
}

// NewCreateAccesspointParamsWithContext creates a new CreateAccesspointParams object
// with the ability to set a context for a request.
func NewCreateAccesspointParamsWithContext(ctx context.Context) *CreateAccesspointParams {
	return &CreateAccesspointParams{
		Context: ctx,
	}
}

// NewCreateAccesspointParamsWithHTTPClient creates a new CreateAccesspointParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAccesspointParamsWithHTTPClient(client *http.Client) *CreateAccesspointParams {
	return &CreateAccesspointParams{
		HTTPClient: client,
	}
}

/*
CreateAccesspointParams contains all the parameters to send to the API endpoint

	for the create accesspoint operation.

	Typically these are written to a http.Request.
*/
type CreateAccesspointParams struct {

	// Body.
	Body CreateAccesspointBody

	/* ClusterID.

	   The ID of the cluster.

	   Format: uint64
	*/
	ClusterID string

	/* ProjectID.

	   The ID of the project. You can get the project ID from the response of [List all accessible projects](#tag/Project/operation/ListProjects).

	   Format: uint64
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create accesspoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAccesspointParams) WithDefaults() *CreateAccesspointParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create accesspoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAccesspointParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create accesspoint params
func (o *CreateAccesspointParams) WithTimeout(timeout time.Duration) *CreateAccesspointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create accesspoint params
func (o *CreateAccesspointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create accesspoint params
func (o *CreateAccesspointParams) WithContext(ctx context.Context) *CreateAccesspointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create accesspoint params
func (o *CreateAccesspointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create accesspoint params
func (o *CreateAccesspointParams) WithHTTPClient(client *http.Client) *CreateAccesspointParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create accesspoint params
func (o *CreateAccesspointParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create accesspoint params
func (o *CreateAccesspointParams) WithBody(body CreateAccesspointBody) *CreateAccesspointParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create accesspoint params
func (o *CreateAccesspointParams) SetBody(body CreateAccesspointBody) {
	o.Body = body
}

// WithClusterID adds the clusterID to the create accesspoint params
func (o *CreateAccesspointParams) WithClusterID(clusterID string) *CreateAccesspointParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the create accesspoint params
func (o *CreateAccesspointParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the create accesspoint params
func (o *CreateAccesspointParams) WithProjectID(projectID string) *CreateAccesspointParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create accesspoint params
func (o *CreateAccesspointParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAccesspointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
