// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreatePrivateLinkEndpointReader is a Reader for the CreatePrivateLinkEndpoint structure.
type CreatePrivateLinkEndpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePrivateLinkEndpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreatePrivateLinkEndpointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreatePrivateLinkEndpointBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreatePrivateLinkEndpointUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreatePrivateLinkEndpointForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreatePrivateLinkEndpointNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCreatePrivateLinkEndpointTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreatePrivateLinkEndpointInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreatePrivateLinkEndpointDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreatePrivateLinkEndpointOK creates a CreatePrivateLinkEndpointOK with default headers values
func NewCreatePrivateLinkEndpointOK() *CreatePrivateLinkEndpointOK {
	return &CreatePrivateLinkEndpointOK{}
}

/*
CreatePrivateLinkEndpointOK describes a response with status code 200, with default header values.

A successful response.
*/
type CreatePrivateLinkEndpointOK struct {
	Payload *CreatePrivateLinkEndpointOKBody
}

// IsSuccess returns true when this create private link endpoint o k response has a 2xx status code
func (o *CreatePrivateLinkEndpointOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create private link endpoint o k response has a 3xx status code
func (o *CreatePrivateLinkEndpointOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint o k response has a 4xx status code
func (o *CreatePrivateLinkEndpointOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create private link endpoint o k response has a 5xx status code
func (o *CreatePrivateLinkEndpointOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link endpoint o k response a status code equal to that given
func (o *CreatePrivateLinkEndpointOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create private link endpoint o k response
func (o *CreatePrivateLinkEndpointOK) Code() int {
	return 200
}

func (o *CreatePrivateLinkEndpointOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointOK %s", 200, payload)
}

func (o *CreatePrivateLinkEndpointOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointOK %s", 200, payload)
}

func (o *CreatePrivateLinkEndpointOK) GetPayload() *CreatePrivateLinkEndpointOKBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointBadRequest creates a CreatePrivateLinkEndpointBadRequest with default headers values
func NewCreatePrivateLinkEndpointBadRequest() *CreatePrivateLinkEndpointBadRequest {
	return &CreatePrivateLinkEndpointBadRequest{}
}

/*
CreatePrivateLinkEndpointBadRequest describes a response with status code 400, with default header values.

A request field is invalid.
*/
type CreatePrivateLinkEndpointBadRequest struct {
	Payload *CreatePrivateLinkEndpointBadRequestBody
}

// IsSuccess returns true when this create private link endpoint bad request response has a 2xx status code
func (o *CreatePrivateLinkEndpointBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create private link endpoint bad request response has a 3xx status code
func (o *CreatePrivateLinkEndpointBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint bad request response has a 4xx status code
func (o *CreatePrivateLinkEndpointBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create private link endpoint bad request response has a 5xx status code
func (o *CreatePrivateLinkEndpointBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link endpoint bad request response a status code equal to that given
func (o *CreatePrivateLinkEndpointBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create private link endpoint bad request response
func (o *CreatePrivateLinkEndpointBadRequest) Code() int {
	return 400
}

func (o *CreatePrivateLinkEndpointBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointBadRequest %s", 400, payload)
}

func (o *CreatePrivateLinkEndpointBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointBadRequest %s", 400, payload)
}

func (o *CreatePrivateLinkEndpointBadRequest) GetPayload() *CreatePrivateLinkEndpointBadRequestBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointUnauthorized creates a CreatePrivateLinkEndpointUnauthorized with default headers values
func NewCreatePrivateLinkEndpointUnauthorized() *CreatePrivateLinkEndpointUnauthorized {
	return &CreatePrivateLinkEndpointUnauthorized{}
}

/*
CreatePrivateLinkEndpointUnauthorized describes a response with status code 401, with default header values.

The API key cannot be authenticated.
*/
type CreatePrivateLinkEndpointUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this create private link endpoint unauthorized response has a 2xx status code
func (o *CreatePrivateLinkEndpointUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create private link endpoint unauthorized response has a 3xx status code
func (o *CreatePrivateLinkEndpointUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint unauthorized response has a 4xx status code
func (o *CreatePrivateLinkEndpointUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create private link endpoint unauthorized response has a 5xx status code
func (o *CreatePrivateLinkEndpointUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link endpoint unauthorized response a status code equal to that given
func (o *CreatePrivateLinkEndpointUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create private link endpoint unauthorized response
func (o *CreatePrivateLinkEndpointUnauthorized) Code() int {
	return 401
}

func (o *CreatePrivateLinkEndpointUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointUnauthorized %s", 401, payload)
}

func (o *CreatePrivateLinkEndpointUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointUnauthorized %s", 401, payload)
}

func (o *CreatePrivateLinkEndpointUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointForbidden creates a CreatePrivateLinkEndpointForbidden with default headers values
func NewCreatePrivateLinkEndpointForbidden() *CreatePrivateLinkEndpointForbidden {
	return &CreatePrivateLinkEndpointForbidden{}
}

/*
CreatePrivateLinkEndpointForbidden describes a response with status code 403, with default header values.

The API key does not have permission to access the resource.
*/
type CreatePrivateLinkEndpointForbidden struct {
	Payload *CreatePrivateLinkEndpointForbiddenBody
}

// IsSuccess returns true when this create private link endpoint forbidden response has a 2xx status code
func (o *CreatePrivateLinkEndpointForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create private link endpoint forbidden response has a 3xx status code
func (o *CreatePrivateLinkEndpointForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint forbidden response has a 4xx status code
func (o *CreatePrivateLinkEndpointForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create private link endpoint forbidden response has a 5xx status code
func (o *CreatePrivateLinkEndpointForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link endpoint forbidden response a status code equal to that given
func (o *CreatePrivateLinkEndpointForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create private link endpoint forbidden response
func (o *CreatePrivateLinkEndpointForbidden) Code() int {
	return 403
}

func (o *CreatePrivateLinkEndpointForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointForbidden %s", 403, payload)
}

func (o *CreatePrivateLinkEndpointForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointForbidden %s", 403, payload)
}

func (o *CreatePrivateLinkEndpointForbidden) GetPayload() *CreatePrivateLinkEndpointForbiddenBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointNotFound creates a CreatePrivateLinkEndpointNotFound with default headers values
func NewCreatePrivateLinkEndpointNotFound() *CreatePrivateLinkEndpointNotFound {
	return &CreatePrivateLinkEndpointNotFound{}
}

/*
CreatePrivateLinkEndpointNotFound describes a response with status code 404, with default header values.

The requested resource does not exist.
*/
type CreatePrivateLinkEndpointNotFound struct {
	Payload *CreatePrivateLinkEndpointNotFoundBody
}

// IsSuccess returns true when this create private link endpoint not found response has a 2xx status code
func (o *CreatePrivateLinkEndpointNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create private link endpoint not found response has a 3xx status code
func (o *CreatePrivateLinkEndpointNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint not found response has a 4xx status code
func (o *CreatePrivateLinkEndpointNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create private link endpoint not found response has a 5xx status code
func (o *CreatePrivateLinkEndpointNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link endpoint not found response a status code equal to that given
func (o *CreatePrivateLinkEndpointNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create private link endpoint not found response
func (o *CreatePrivateLinkEndpointNotFound) Code() int {
	return 404
}

func (o *CreatePrivateLinkEndpointNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointNotFound %s", 404, payload)
}

func (o *CreatePrivateLinkEndpointNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointNotFound %s", 404, payload)
}

func (o *CreatePrivateLinkEndpointNotFound) GetPayload() *CreatePrivateLinkEndpointNotFoundBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointTooManyRequests creates a CreatePrivateLinkEndpointTooManyRequests with default headers values
func NewCreatePrivateLinkEndpointTooManyRequests() *CreatePrivateLinkEndpointTooManyRequests {
	return &CreatePrivateLinkEndpointTooManyRequests{}
}

/*
CreatePrivateLinkEndpointTooManyRequests describes a response with status code 429, with default header values.

You have exceed the rate limit.
*/
type CreatePrivateLinkEndpointTooManyRequests struct {
	Payload *CreatePrivateLinkEndpointTooManyRequestsBody
}

// IsSuccess returns true when this create private link endpoint too many requests response has a 2xx status code
func (o *CreatePrivateLinkEndpointTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create private link endpoint too many requests response has a 3xx status code
func (o *CreatePrivateLinkEndpointTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint too many requests response has a 4xx status code
func (o *CreatePrivateLinkEndpointTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this create private link endpoint too many requests response has a 5xx status code
func (o *CreatePrivateLinkEndpointTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this create private link endpoint too many requests response a status code equal to that given
func (o *CreatePrivateLinkEndpointTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the create private link endpoint too many requests response
func (o *CreatePrivateLinkEndpointTooManyRequests) Code() int {
	return 429
}

func (o *CreatePrivateLinkEndpointTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointTooManyRequests %s", 429, payload)
}

func (o *CreatePrivateLinkEndpointTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointTooManyRequests %s", 429, payload)
}

func (o *CreatePrivateLinkEndpointTooManyRequests) GetPayload() *CreatePrivateLinkEndpointTooManyRequestsBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointTooManyRequestsBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointInternalServerError creates a CreatePrivateLinkEndpointInternalServerError with default headers values
func NewCreatePrivateLinkEndpointInternalServerError() *CreatePrivateLinkEndpointInternalServerError {
	return &CreatePrivateLinkEndpointInternalServerError{}
}

/*
CreatePrivateLinkEndpointInternalServerError describes a response with status code 500, with default header values.

Server error.
*/
type CreatePrivateLinkEndpointInternalServerError struct {
	Payload *CreatePrivateLinkEndpointInternalServerErrorBody
}

// IsSuccess returns true when this create private link endpoint internal server error response has a 2xx status code
func (o *CreatePrivateLinkEndpointInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create private link endpoint internal server error response has a 3xx status code
func (o *CreatePrivateLinkEndpointInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create private link endpoint internal server error response has a 4xx status code
func (o *CreatePrivateLinkEndpointInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create private link endpoint internal server error response has a 5xx status code
func (o *CreatePrivateLinkEndpointInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create private link endpoint internal server error response a status code equal to that given
func (o *CreatePrivateLinkEndpointInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create private link endpoint internal server error response
func (o *CreatePrivateLinkEndpointInternalServerError) Code() int {
	return 500
}

func (o *CreatePrivateLinkEndpointInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointInternalServerError %s", 500, payload)
}

func (o *CreatePrivateLinkEndpointInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] createPrivateLinkEndpointInternalServerError %s", 500, payload)
}

func (o *CreatePrivateLinkEndpointInternalServerError) GetPayload() *CreatePrivateLinkEndpointInternalServerErrorBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePrivateLinkEndpointDefault creates a CreatePrivateLinkEndpointDefault with default headers values
func NewCreatePrivateLinkEndpointDefault(code int) *CreatePrivateLinkEndpointDefault {
	return &CreatePrivateLinkEndpointDefault{
		_statusCode: code,
	}
}

/*
CreatePrivateLinkEndpointDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CreatePrivateLinkEndpointDefault struct {
	_statusCode int

	Payload *CreatePrivateLinkEndpointDefaultBody
}

// IsSuccess returns true when this create private link endpoint default response has a 2xx status code
func (o *CreatePrivateLinkEndpointDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create private link endpoint default response has a 3xx status code
func (o *CreatePrivateLinkEndpointDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create private link endpoint default response has a 4xx status code
func (o *CreatePrivateLinkEndpointDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create private link endpoint default response has a 5xx status code
func (o *CreatePrivateLinkEndpointDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create private link endpoint default response a status code equal to that given
func (o *CreatePrivateLinkEndpointDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create private link endpoint default response
func (o *CreatePrivateLinkEndpointDefault) Code() int {
	return o._statusCode
}

func (o *CreatePrivateLinkEndpointDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] CreatePrivateLinkEndpoint default %s", o._statusCode, payload)
}

func (o *CreatePrivateLinkEndpointDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1beta/projects/{project_id}/clusters/{cluster_id}/accesspoints/{accesspoint_id}/privateLinkEndpoints][%d] CreatePrivateLinkEndpoint default %s", o._statusCode, payload)
}

func (o *CreatePrivateLinkEndpointDefault) GetPayload() *CreatePrivateLinkEndpointDefaultBody {
	return o.Payload
}

func (o *CreatePrivateLinkEndpointDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreatePrivateLinkEndpointDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CreatePrivateLinkEndpointBadRequestBody create private link endpoint bad request body
swagger:model CreatePrivateLinkEndpointBadRequestBody
*/
type CreatePrivateLinkEndpointBadRequestBody struct {

	// code
	//
	// Error code returned with this error.
	Code int64 `json:"code,omitempty"`

	// details
	//
	// Error details returned with this error.
	Details []string `json:"details"`

	// message
	//
	// Error message returned with this error.
	Message string `json:"message,omitempty"`
}

// Validate validates this create private link endpoint bad request body
func (o *CreatePrivateLinkEndpointBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create private link endpoint bad request body based on context it is used
func (o *CreatePrivateLinkEndpointBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointBody CreatePrivateLinkEndpointReq
//
// CreatePrivateLinkEndpointReq is the request for creating a private link endpoint for a cluster.
swagger:model CreatePrivateLinkEndpointBody
*/
type CreatePrivateLinkEndpointBody struct {

	// The format of the private endpoint name varies by cloud provider: `"vpce-xxxx"` for AWS and `"projects/xxx/regions/xxx/forwardingRules/xxx"` for Google Cloud.
	// Example: vpce-01234567890123456
	// Required: true
	EndpointName *string `json:"endpoint_name"`
}

// Validate validates this create private link endpoint body
func (o *CreatePrivateLinkEndpointBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEndpointName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePrivateLinkEndpointBody) validateEndpointName(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"endpoint_name", "body", o.EndpointName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create private link endpoint body based on context it is used
func (o *CreatePrivateLinkEndpointBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointDefaultBody create private link endpoint default body
swagger:model CreatePrivateLinkEndpointDefaultBody
*/
type CreatePrivateLinkEndpointDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*CreatePrivateLinkEndpointDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create private link endpoint default body
func (o *CreatePrivateLinkEndpointDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePrivateLinkEndpointDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("CreatePrivateLinkEndpoint default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("CreatePrivateLinkEndpoint default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this create private link endpoint default body based on the context it is used
func (o *CreatePrivateLinkEndpointDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePrivateLinkEndpointDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("CreatePrivateLinkEndpoint default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("CreatePrivateLinkEndpoint default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointDefaultBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointDefaultBodyDetailsItems0 create private link endpoint default body details items0
swagger:model CreatePrivateLinkEndpointDefaultBodyDetailsItems0
*/
type CreatePrivateLinkEndpointDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// create private link endpoint default body details items0
	CreatePrivateLinkEndpointDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *CreatePrivateLinkEndpointDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv CreatePrivateLinkEndpointDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.CreatePrivateLinkEndpointDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o CreatePrivateLinkEndpointDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.CreatePrivateLinkEndpointDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.CreatePrivateLinkEndpointDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this create private link endpoint default body details items0
func (o *CreatePrivateLinkEndpointDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create private link endpoint default body details items0 based on context it is used
func (o *CreatePrivateLinkEndpointDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointForbiddenBody create private link endpoint forbidden body
swagger:model CreatePrivateLinkEndpointForbiddenBody
*/
type CreatePrivateLinkEndpointForbiddenBody struct {

	// code
	//
	// Error code returned with this error.
	Code int64 `json:"code,omitempty"`

	// details
	//
	// Error details returned with this error.
	Details []string `json:"details"`

	// message
	//
	// Error message returned with this error.
	Message string `json:"message,omitempty"`
}

// Validate validates this create private link endpoint forbidden body
func (o *CreatePrivateLinkEndpointForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create private link endpoint forbidden body based on context it is used
func (o *CreatePrivateLinkEndpointForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointForbiddenBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointInternalServerErrorBody create private link endpoint internal server error body
swagger:model CreatePrivateLinkEndpointInternalServerErrorBody
*/
type CreatePrivateLinkEndpointInternalServerErrorBody struct {

	// code
	//
	// Error code returned with this error.
	Code int64 `json:"code,omitempty"`

	// details
	//
	// Error details returned with this error.
	Details []string `json:"details"`

	// message
	//
	// Error message returned with this error.
	Message string `json:"message,omitempty"`
}

// Validate validates this create private link endpoint internal server error body
func (o *CreatePrivateLinkEndpointInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create private link endpoint internal server error body based on context it is used
func (o *CreatePrivateLinkEndpointInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointNotFoundBody create private link endpoint not found body
swagger:model CreatePrivateLinkEndpointNotFoundBody
*/
type CreatePrivateLinkEndpointNotFoundBody struct {

	// code
	//
	// Error code returned with this error.
	Code int64 `json:"code,omitempty"`

	// details
	//
	// Error details returned with this error.
	Details []string `json:"details"`

	// message
	//
	// Error message returned with this error.
	Message string `json:"message,omitempty"`
}

// Validate validates this create private link endpoint not found body
func (o *CreatePrivateLinkEndpointNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create private link endpoint not found body based on context it is used
func (o *CreatePrivateLinkEndpointNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointNotFoundBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointOKBody CreatePrivateLinkEndpointResp
//
// CreatePrivateLinkEndpointResp is the response for creating a private link endpoint for a cluster.
swagger:model CreatePrivateLinkEndpointOKBody
*/
type CreatePrivateLinkEndpointOKBody struct {

	// The ID of the private link endpoint.
	// Example: 1
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this create private link endpoint o k body
func (o *CreatePrivateLinkEndpointOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreatePrivateLinkEndpointOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("createPrivateLinkEndpointOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create private link endpoint o k body based on context it is used
func (o *CreatePrivateLinkEndpointOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointOKBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreatePrivateLinkEndpointTooManyRequestsBody create private link endpoint too many requests body
swagger:model CreatePrivateLinkEndpointTooManyRequestsBody
*/
type CreatePrivateLinkEndpointTooManyRequestsBody struct {

	// code
	//
	// Error code returned with this error.
	Code int64 `json:"code,omitempty"`

	// details
	//
	// Error details returned with this error.
	Details []string `json:"details"`

	// message
	//
	// Error message returned with this error.
	Message string `json:"message,omitempty"`
}

// Validate validates this create private link endpoint too many requests body
func (o *CreatePrivateLinkEndpointTooManyRequestsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create private link endpoint too many requests body based on context it is used
func (o *CreatePrivateLinkEndpointTooManyRequestsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointTooManyRequestsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePrivateLinkEndpointTooManyRequestsBody) UnmarshalBinary(b []byte) error {
	var res CreatePrivateLinkEndpointTooManyRequestsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
