// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreatePrivateEndpointParams creates a new CreatePrivateEndpointParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePrivateEndpointParams() *CreatePrivateEndpointParams {
	return &CreatePrivateEndpointParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePrivateEndpointParamsWithTimeout creates a new CreatePrivateEndpointParams object
// with the ability to set a timeout on a request.
func NewCreatePrivateEndpointParamsWithTimeout(timeout time.Duration) *CreatePrivateEndpointParams {
	return &CreatePrivateEndpointParams{
		timeout: timeout,
	}
}

// NewCreatePrivateEndpointParamsWithContext creates a new CreatePrivateEndpointParams object
// with the ability to set a context for a request.
func NewCreatePrivateEndpointParamsWithContext(ctx context.Context) *CreatePrivateEndpointParams {
	return &CreatePrivateEndpointParams{
		Context: ctx,
	}
}

// NewCreatePrivateEndpointParamsWithHTTPClient creates a new CreatePrivateEndpointParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePrivateEndpointParamsWithHTTPClient(client *http.Client) *CreatePrivateEndpointParams {
	return &CreatePrivateEndpointParams{
		HTTPClient: client,
	}
}

/*
CreatePrivateEndpointParams contains all the parameters to send to the API endpoint

	for the create private endpoint operation.

	Typically these are written to a http.Request.
*/
type CreatePrivateEndpointParams struct {

	/* ClusterID.

	   The ID of the cluster.

	   Format: uint64
	*/
	ClusterID string

	// PrivateEndpoint.
	PrivateEndpoint CreatePrivateEndpointBody

	/* ProjectID.

	   The ID of the project. You can get the project ID from the response of [List all accessible projects](#tag/Project/operation/ListProjects).

	   Format: uint64
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create private endpoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePrivateEndpointParams) WithDefaults() *CreatePrivateEndpointParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create private endpoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePrivateEndpointParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create private endpoint params
func (o *CreatePrivateEndpointParams) WithTimeout(timeout time.Duration) *CreatePrivateEndpointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create private endpoint params
func (o *CreatePrivateEndpointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create private endpoint params
func (o *CreatePrivateEndpointParams) WithContext(ctx context.Context) *CreatePrivateEndpointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create private endpoint params
func (o *CreatePrivateEndpointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create private endpoint params
func (o *CreatePrivateEndpointParams) WithHTTPClient(client *http.Client) *CreatePrivateEndpointParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create private endpoint params
func (o *CreatePrivateEndpointParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the create private endpoint params
func (o *CreatePrivateEndpointParams) WithClusterID(clusterID string) *CreatePrivateEndpointParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the create private endpoint params
func (o *CreatePrivateEndpointParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithPrivateEndpoint adds the privateEndpoint to the create private endpoint params
func (o *CreatePrivateEndpointParams) WithPrivateEndpoint(privateEndpoint CreatePrivateEndpointBody) *CreatePrivateEndpointParams {
	o.SetPrivateEndpoint(privateEndpoint)
	return o
}

// SetPrivateEndpoint adds the privateEndpoint to the create private endpoint params
func (o *CreatePrivateEndpointParams) SetPrivateEndpoint(privateEndpoint CreatePrivateEndpointBody) {
	o.PrivateEndpoint = privateEndpoint
}

// WithProjectID adds the projectID to the create private endpoint params
func (o *CreatePrivateEndpointParams) WithProjectID(projectID string) *CreatePrivateEndpointParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create private endpoint params
func (o *CreatePrivateEndpointParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePrivateEndpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.PrivateEndpoint); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
