// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPrivateLinkEndpointsParams creates a new ListPrivateLinkEndpointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPrivateLinkEndpointsParams() *ListPrivateLinkEndpointsParams {
	return &ListPrivateLinkEndpointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPrivateLinkEndpointsParamsWithTimeout creates a new ListPrivateLinkEndpointsParams object
// with the ability to set a timeout on a request.
func NewListPrivateLinkEndpointsParamsWithTimeout(timeout time.Duration) *ListPrivateLinkEndpointsParams {
	return &ListPrivateLinkEndpointsParams{
		timeout: timeout,
	}
}

// NewListPrivateLinkEndpointsParamsWithContext creates a new ListPrivateLinkEndpointsParams object
// with the ability to set a context for a request.
func NewListPrivateLinkEndpointsParamsWithContext(ctx context.Context) *ListPrivateLinkEndpointsParams {
	return &ListPrivateLinkEndpointsParams{
		Context: ctx,
	}
}

// NewListPrivateLinkEndpointsParamsWithHTTPClient creates a new ListPrivateLinkEndpointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPrivateLinkEndpointsParamsWithHTTPClient(client *http.Client) *ListPrivateLinkEndpointsParams {
	return &ListPrivateLinkEndpointsParams{
		HTTPClient: client,
	}
}

/*
ListPrivateLinkEndpointsParams contains all the parameters to send to the API endpoint

	for the list private link endpoints operation.

	Typically these are written to a http.Request.
*/
type ListPrivateLinkEndpointsParams struct {

	/* AccesspointID.

	   The ID of the accesspoint.

	   Format: uint64
	*/
	AccesspointID string

	/* ClusterID.

	   The ID of the cluster.

	   Format: uint64
	*/
	ClusterID string

	/* ProjectID.

	   The ID of the project.

	   Format: uint64
	*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list private link endpoints params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPrivateLinkEndpointsParams) WithDefaults() *ListPrivateLinkEndpointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list private link endpoints params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPrivateLinkEndpointsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) WithTimeout(timeout time.Duration) *ListPrivateLinkEndpointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) WithContext(ctx context.Context) *ListPrivateLinkEndpointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) WithHTTPClient(client *http.Client) *ListPrivateLinkEndpointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccesspointID adds the accesspointID to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) WithAccesspointID(accesspointID string) *ListPrivateLinkEndpointsParams {
	o.SetAccesspointID(accesspointID)
	return o
}

// SetAccesspointID adds the accesspointId to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) SetAccesspointID(accesspointID string) {
	o.AccesspointID = accesspointID
}

// WithClusterID adds the clusterID to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) WithClusterID(clusterID string) *ListPrivateLinkEndpointsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) WithProjectID(projectID string) *ListPrivateLinkEndpointsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list private link endpoints params
func (o *ListPrivateLinkEndpointsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListPrivateLinkEndpointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accesspoint_id
	if err := r.SetPathParam("accesspoint_id", o.AccesspointID); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
