// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProviderRegionsParams creates a new ListProviderRegionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProviderRegionsParams() *ListProviderRegionsParams {
	return &ListProviderRegionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProviderRegionsParamsWithTimeout creates a new ListProviderRegionsParams object
// with the ability to set a timeout on a request.
func NewListProviderRegionsParamsWithTimeout(timeout time.Duration) *ListProviderRegionsParams {
	return &ListProviderRegionsParams{
		timeout: timeout,
	}
}

// NewListProviderRegionsParamsWithContext creates a new ListProviderRegionsParams object
// with the ability to set a context for a request.
func NewListProviderRegionsParamsWithContext(ctx context.Context) *ListProviderRegionsParams {
	return &ListProviderRegionsParams{
		Context: ctx,
	}
}

// NewListProviderRegionsParamsWithHTTPClient creates a new ListProviderRegionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListProviderRegionsParamsWithHTTPClient(client *http.Client) *ListProviderRegionsParams {
	return &ListProviderRegionsParams{
		HTTPClient: client,
	}
}

/*
ListProviderRegionsParams contains all the parameters to send to the API endpoint

	for the list provider regions operation.

	Typically these are written to a http.Request.
*/
type ListProviderRegionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list provider regions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProviderRegionsParams) WithDefaults() *ListProviderRegionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list provider regions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProviderRegionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list provider regions params
func (o *ListProviderRegionsParams) WithTimeout(timeout time.Duration) *ListProviderRegionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list provider regions params
func (o *ListProviderRegionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list provider regions params
func (o *ListProviderRegionsParams) WithContext(ctx context.Context) *ListProviderRegionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list provider regions params
func (o *ListProviderRegionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list provider regions params
func (o *ListProviderRegionsParams) WithHTTPClient(client *http.Client) *ListProviderRegionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list provider regions params
func (o *ListProviderRegionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListProviderRegionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
